Wwwision:
  Neos:
    MailChimp:
      apiKey: ''
Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'Wwwision.Neos.MailChimp:MailChimpSubscriptionFinisher':
            implementationClassName: Wwwision\Neos\MailChimp\Form\Finishers\MailChimpSubscriptionFinisher
        validatorPresets:
          'Wwwision.Neos.MailChimp:UniqueSubscription':
            implementationClassName: Wwwision\Neos\MailChimp\Validation\Validator\UniqueSubscriptionValidator
  Neos:
    modules:
      administration:
        submodules:
          mailchimp:
            label: MailChimp
            controller: Wwwision\Neos\MailChimp\Controller\Module\MailChimpController
            description: 'This module provides you with a simple overview of your MailChimp® lists and allows for (un)subscribing members'
            icon: icon-bullhorn
            resource: 'Wwwision.Neos.MailChimp:BackendModuleMailChimp'
